# Generated by Django 4.2.dev20220628195651 on 2022-06-29 21:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_name', models.CharField(max_length=255)),
                ('_balance', models.IntegerField()),
                ('_credit_line', models.IntegerField()),
                ('_password', models.CharField(max_length=64)),
                ('_personal_info', models.CharField(max_length=32)),
            ],
        ),
    ]
