# Generated by Django 4.2.dev20220628195651 on 2022-06-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiContaCorrente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='_password',
            field=models.CharField(max_length=256),
        ),
    ]
