# Generated by Django 4.0.5 on 2022-06-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiContaCorrente', '0002_alter_client__password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_date', models.DateField()),
                ('_type', models.CharField(max_length=32)),
                ('_value', models.IntegerField()),
                ('_description', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='_password',
        ),
        migrations.RemoveField(
            model_name='client',
            name='_personal_info',
        ),
        migrations.AddField(
            model_name='client',
            name='_transaction_history',
            field=models.ManyToManyField(to='apiContaCorrente.transaction'),
        ),
    ]
