# Generated by Django 4.0.5 on 2022-06-30 07:56

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apiContaCorrente', '0003_transaction_remove_client__password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='_transaction_history',
        ),
        migrations.AddField(
            model_name='client',
            name='_transaction_history',
            field=jsonfield.fields.JSONField(default=None),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
